#!/bin/bash
#PBS -N PBS-GEM-Init
#PBS -l select=1:ncpus=1:mem=1gb,walltime=1:00:00

cd ${PBS_O_WORKDIR}

cd Templates

BASEDIR=$(cat basedir.txt)

tar -xf $BASEDIR/Software/sratoolkit.current-centos_linux64.tar.gz -C $BASEDIR\
/Software

unzip $BASEDIR/Software/Trimmomatic-0.38.zip -d $BASEDIR/Software

tar -xf $BASEDIR/Software/samtools-1.8.tar.gz -C $BASEDIR/Software
unzip $BASEDIR/Software/hisat2-2.1.0-Linux_x86_64.zip -d \
$BASEDIR/Software

tar -xf $BASEDIR/Software/stringtie-1.3.4d.Linux_x86_64.tar.gz -C \
$BASEDIR/Software

