#!/bin/bash
#PBS -N PBS-GEM-Init
#PBS -l select=1:ncpus=1:mem=1gb,walltime=1:00:00

cd ${PBS_O_WORKDIR}

cd Templates

BASEDIR=$(cat basedir.txt)

tar -xf $BASEDIR/Software/sratoolkit.2.8.1-centos_linux64.tar.gz -C $BASEDIR\
/Software

unzip $BASEDIR/Software/Trimmomatic-0.36.zip -d $BASEDIR/Software

tar -xf $BASEDIR/Software/samtools-1.3.1.tar.gz -C $BASEDIR/Software
unzip $BASEDIR/Software/hisat2-2.0.5-Linux_x86_64.zip -d \
$BASEDIR/Software

tar -xf $BASEDIR/Software/stringtie-1.3.1c.Linux_x86_64.tar.gz -C \
$BASEDIR/Software

